<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <link name="base_link"/>

    <link name="body">
        <visual>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}"/>
            </geometry>
            <origin xyz="0 0 ${body_height / 2.0}" rpy="0 0 0"/>
            <material name="blue"/>
        </visual>

        <collision>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}"/>
            </geometry>
            <origin xyz="0 0 ${body_height / 2.0}" rpy="0 0 0"/>
        </collision>

        <xacro:box_inertia m="${body_mass}" l="${body_length}" w="${body_width}" h="${body_height}" 
                           xyz="0 0 ${body_height / 2.0}" rpy="0 0 0"/>
    </link>

    <xacro:macro name="wheel" params="prefix">
        <link name="${prefix}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <material name="gray" />
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${wheel_radius}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
            </collision>
            <xacro:wheel_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_thickness}" 
                                    xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
        </link>
    </xacro:macro>

    <xacro:wheel prefix="right" />
    <xacro:wheel prefix="left" />

    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="gray"/>
        </visual>

        <collision>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>

        <xacro:caster_inertia m="${caster_mass}" r="${caster_radius}" 
                              xyz="0 0 0" rpy="0 0 0"/>
    </link>

    <joint name="base_link_to_body" type="fixed">
        <parent link="base_link"/>
        <child link="body"/>
        <origin xyz="0 0 ${body_ground_offset_z}" rpy="0 0 0"/>
    </joint>

    <joint name="left_wheel_joint" type="continuous">
        <parent link="body"/>
        <child link="left_wheel"/>
        <origin xyz="${wheel_joint_offset_x} ${left_wheel_joint_offset_y} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="right_wheel_joint" type="continuous">
        <parent link="body"/>
        <child link="right_wheel"/>
        <origin xyz="${wheel_joint_offset_x} ${right_wheel_joint_offset_y} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="caster_wheel_joint" type="fixed">
        <parent link="body"/>
        <child link="caster_wheel"/>
        <origin xyz="${caster_wheel_joint_offset_x} 0 ${caster_wheel_joint_offset_z}" rpy="0 0 0"/>
        <!-- <axis xyz="0 1 0"/> -->
    </joint>

</robot>