<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


    <xacro:property name="body_length" value="0.6"/>
    <xacro:property name="body_width" value="0.4"/>
    <xacro:property name="body_height" value="0.2"/>
    <xacro:property name="wheel_radius" value="${body_height/2.0}"/>
    <xacro:property name="wheel_thickness" value="0.05"/>
    <xacro:property name="caster_radius" value="0.05"/>


</robot>